### PR TITLE
[admin][3wny1nq] implementUI

### PR DESCRIPTION
**Pull request by CuongXuanLe**
check Admin UI pleaseeeeeeeeee, include:
 - Login
 - Home Admin
 - Guide Page
 - Navigation
 - Footer
 - Change pwd

### CODE REVIEW

**Comment by thaiikhang** [comment]
Missing title of section & blog :(

**Review by thaiikhang — CHANGES_REQUESTED** [review]
Missing title of section & blog :(

**Comment by CuongXuanLe** [comment]
gogo

**Review by thaiikhang — APPROVED** [review]
oke ong ✌️

**Pull request merged**
